# Generated by Django 6.0.4 on 2026-04-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='stock_minimum',
            field=models.IntegerField(default=5, help_text="Seuil d'alerte stock bas"),
        ),
    ]
