# Generated by Django 6.0.4 on 2026-04-23 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='code',
            field=models.CharField(editable=False, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='userlicense',
            name='license_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='licenses.licensekey'),
        ),
    ]
